---
version: "2.1"
services:
  tobira-server:
    image: scz10/tobira:latest
    network_mode: "host"
    container_name: tobira-server
    hostname: tobira-server #optional
    environment:
      - GATEWAY_PORTS=yes
      - TCP_FORWARDING=all
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=secret
      - USER_NAME=tobira
    restart: unless-stopped